#!/usr/bin/env bash

set -e
set -o nounset
set -o pipefail

script_dir=$(
    cd "$(dirname "$0")"
    pwd -P
)

tools_dir="$script_dir/.tools"
deploy_dir="$script_dir/.deploy"
mkdir -p "$tools_dir" "$deploy_dir"

export CR_PACKAGE_PATH="$deploy_dir"

target_install() {
    os_name=$(uname | tr '[:upper:]' '[:lower:]')
    curl -sSL https://github.com/helm/chart-releaser/releases/download/v"$CR_VERSION"/chart-releaser_"$CR_VERSION"_"$os_name"_amd64.tar.gz |
        tar -C "$tools_dir" -xzf -
}

"$tools_dir"/cr version 2>/dev/null || target_install
"$tools_dir"/cr index --index-path index.yaml
