#!/usr/bin/env bash

set -e
set -o nounset
set -o pipefail

script_dir=$(
    cd "$(dirname "$0")"
    pwd -P
)
tools_dir="$script_dir/.tools"
deploy_dir="$script_dir/.deploy"
mkdir -p "$tools_dir" "$deploy_dir"

export CR_PACKAGE_PATH="$deploy_dir"

printb() {
    local string="$1"
    builtin printf '%b%b%b' '\033[0;34m' "$string" '\033[0m'
}

target_install() {
    os_name=$(uname | tr '[:upper:]' '[:lower:]')
    curl -sSL https://get.helm.sh/helm-v"$HELM_VERSION"-"$os_name"-amd64.tar.gz |
        tar -C "$tools_dir" -xzf -
    mv "$tools_dir"/"$os_name"-amd64/helm "$tools_dir"/helm
    curl -sSL https://github.com/helm/chart-releaser/releases/download/v"$CR_VERSION"/chart-releaser_"$CR_VERSION"_"$os_name"_amd64.tar.gz |
        tar -C "$tools_dir" -xzf -
}

printb "install cr:\n"
"$tools_dir"/cr version >/dev/null 2>&1 || target_install
"$tools_dir"/cr version

printb "create index:\n"
"$tools_dir"/cr index --index-path index.yaml
