kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "version-monitor.fullname" . }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "version-monitor.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "version-monitor.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
