apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "version-monitor.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "version-monitor.name" . }}
    helm.sh/chart: {{ include "version-monitor.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "version-monitor.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/env: {{ include (print $.Template.BasePath "/config-map-env.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/config-map-config.yaml") . | sha256sum }}
      labels:
        pod-replica-count-insufficient-check: "false"
        app.kubernetes.io/name: {{ include "version-monitor.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "version-monitor.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "version-monitor.image" .Values.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "version-monitor.fullname" . }}-env
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ include "version-monitor.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
